### ISSUE TITLE
[Bug]: libva error: vaGetDriverNameByIndex() failed with unknown libva error (Ubuntu 22.04.2 LTS)

### ISSUE THREAD

**Issue by lothereus** [NativePHP/laravel#136]
### What happened?

Running `php artisan native:serve` give a libva error

```
Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…

> NativePHP@1.0.0 dev
> electron-vite dev --watch

vite v4.3.9 building for development...

watching for file changes...

build started...
✓ 4 modules transformed.
out/main/index.js  0.55 kB
built in 43ms.

build the electron main process successfully

-----

vite v4.3.9 building for development...

watching for file changes...

build started...
transforming (1) src/preload/index.js"contextBridge" and "ipcRenderer" are imported from external module "electron" but never used in "src/preload/index.js".
✓ 1 modules transformed.
out/preload/index.js  0.70 kB
built in 7ms.

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...
```

Then the error occurred...

```
(node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setIcon')
    at NativePHP.<anonymous> (/home/me/myapp/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/index.js:79:26)
    at Generator.next (<anonymous>)
    at /home/me/myapp/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/me/myapp/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/index.js:4:12)
    at /home/me/myapp/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/index.js:76:36
(Use `electron --trace-warnings ...` to show where the warning was created)

(node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

### How to reproduce the bug

I just follow the installation instruction on nativephp website
Trying to run `php artisan native:serve` gave a permission error
Trying to run as root gave a root warning issue
Then `chown -R current:current` the whole installation directory
Then run again `php artisan native:serve`

### Package Version

1.0.0

### PHP Version

8.1.21

### Laravel Version

10.16.1

### Which operating systems does with happen with?

Linux

### Notes

Node 20.2.0
NPM 9.8.1

**Comment by xmedeko** [comment]
@simonhamp The Electron issue you have mentioned has been closed half a year ago due to inactivity. Open a new issue, if you experience the problem.
