### ISSUE TITLE
[Bug]: The application fails to build on Mac

### ISSUE THREAD

**Issue by driade** [NativePHP/laravel#197]
### What happened?

The application fails to build on Mac

### How to reproduce the bug

Run ```
php artisan native:build mac
```

### Package Version

^0.4.0

### PHP Version

8.2.0

### Laravel Version

^10.10

### Node Version

20.5.1

### Which operating systems does with happen with?

macOS

### Notes

...
Binary Source:  /Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/php-bin/bin/mac/x64
Binary Filename:  php
Copying PHP file(s) from /Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/php-bin/bin/mac/x64 to /Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/electron/resources/js/resources/php
Error copying PHP binary Error: ENOENT: no such file or directory, stat '/Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/php-bin/bin/mac/x64'
    at Object.statSync (node:fs:1706:3)
    at Object.statSync (/Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/electron/resources/js/node_modules/graceful-fs/polyfills.js:318:34)
    at statSync (/Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/electron/resources/js/node_modules/fs-extra/lib/util/stat.js:10:52)
    at getStatsSync (/Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/electron/resources/js/node_modules/fs-extra/lib/util/stat.js:24:19)
    at Object.checkPathsSync (/Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/electron/resources/js/node_modules/fs-extra/lib/util/stat.js:49:33)
    at copySync (/Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/electron/resources/js/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at Object.<anonymous> (/Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/electron/resources/js/php.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/php-bin/bin/mac/x64'
}
Copied certificate file to /Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/electron/resources/js/resources/cacert.pem

> NativePHP@1.0.0 build
> electron-vite build

vite v4.4.7 building for production...
✓ 3 modules transformed.
✓ built in 42ms
Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
file: /Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/electron/resources/js/src/main/index.js
error during build:
RollupError: Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
    at error (file:///Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:24674:24)
    at file:///Users/davidfernandez/htdocs/gasgas/src/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:24636:26

**Comment by eugenefvdm** [comment]
Please see https://github.com/NativePHP/laravel/issues/187

The error I receive building for Mac M chip on Mac M chip below were resolved by this command:

```bash
cp -r vendor/nativephp/php-bin/bin/mac/arm64 vendor/nativephp/php-bin/bin/mac/x64
```

Errors resolved by above `cp`:

```javascript
Copying PHP file(s) from /Users/eugene/Code/native-app/vendor/nativephp/php-bin/bin/mac/x64 to /Users/eugene/Code/native-app/vendor/nativephp/electron/resources/js/resources/php
Error copying PHP binary Error: ENOENT: no such file or directory, stat '/Users/eugene/Code/native-app/vendor/nativephp/php-bin/bin/mac/x64'


Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
file: /Users/eugene/Code/native-app/vendor/nativephp/electron/resources/js/src/main/index.js
```

**Comment by driade** [comment]
Thank you very much @eugenefvdm
