### ISSUE TITLE
[Bug]: Building and publish for Windows from Mac

### ISSUE THREAD

**Issue by bomshteyn** [NativePHP/laravel#202]
### What happened?

I have run into 2 issues:
### Installing Windows EXE file:
When i run `php artisan native:build win` it builds an EXE version. 
But when i try to install it on Windows 11 i get an error: Missing Shortcut. 

### Publishing to Spaces
I tried to use `php artisan native:publish win`, but it crashes if i run `php artisan native:publish` it doesn't crash but doesn't build and upload a windows version. Here is the error i get when i run `php artisan native:publish win`:

```
NativePHP@1.0.0 publish:mac-arm
> cross-env npm run build && cross-env electron-builder -p always --mac --config --arm64 -p always


> NativePHP@1.0.0 build
> electron-vite build

vite v4.4.9 building for production...
✓ 3 modules transformed.
✓ built in 32ms

Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
file: /Users/MyName/PhpstormProjects/zms/vendor/nativephp/electron/resources/js/src/main/index.js
error during build:
RollupError: Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
    at error (file:///Users/MyName/PhpstormProjects/zms/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/MyName/PhpstormProjects/zms/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:24778:24)
    at file:///Users/MyName/PhpstormProjects/zms/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:24740:26
```

### 1
When i run `php artisan native:build win` it builds an EXE version. 
But when i try to install it on Windows 11 i get an error: Missing Shortcut. 

### 2
Here is the error i get when i run `php artisan native:publish win`:

```
NativePHP@1.0.0 publish:mac-arm
> cross-env npm run build && cross-env electron-builder -p always --mac --config --arm64 -p always


> NativePHP@1.0.0 build
> electron-vite build

vite v4.4.9 building for production...
✓ 3 modules transformed.
✓ built in 32ms

Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
file: /Users/MyName/PhpstormProjects/zms/vendor/nativephp/electron/resources/js/src/main/index.js
error during build:
RollupError: Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
    at error (file:///Users/MyName/PhpstormProjects/zms/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/MyName/PhpstormProjects/zms/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:24778:24)
    at file:///Users/MyName/PhpstormProjects/zms/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:24740:26
```

### Package Version

0.4.0

### PHP Version

8.1.23

### Laravel Version

10.21.0

### Node Version

20.5.1

### Which operating systems does with happen with?

macOS

### Notes

Mac with Apple M2 Pro chip

**Comment by jhernandezquezada** [comment]
Could you solve the problem? I'm experiencing the same thing.

**Comment by simonhamp** [comment]
Building and publishing for Windows hasn't been officially supported until now.

Please update to nativephp/electron v0.6 and try again.
