### ISSUE TITLE
[Bug]:  app.dock.setIcon Error

### ISSUE THREAD

**Issue by elsayed85** [NativePHP/laravel#21]
### What happened?

(node:59338) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setIcon')
    at NativePHP.<anonymous> (/home/sayed/Desktop/DesktopApps/ray/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/index.js:81:26)
    at Generator.next (<anonymous>)
    at /home/sayed/Desktop/DesktopApps/ray/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sayed/Desktop/DesktopApps/ray/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/index.js:4:12)
    at /home/sayed/Desktop/DesktopApps/ray/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/index.js:78:36
(Use `electron --trace-warnings ...` to show where the warning was created)

### How to reproduce the bug

php artisan native:serve

### Package Version

0.10

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by septianinet** [comment]
I had the same issue

**Comment by mpociot** [comment]
Fixed it, as dock.setIcon is only available on macOS
