### ISSUE TITLE
Error while trying to build app: Could not resolve "../../resources/php/php?asset&asarUnpack"

### ISSUE THREAD

**Issue by NBA707** [NativePHP/laravel#291]
Not sure what steps to do pre: php artisan native:build so that resources has a PHP directory, it does not currently:

`Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
file: /Users/database/Projects/nativephp/vendor/nativephp/electron/resources/js/src/main/index.js
error during build:
RollupError: Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
    at error (file:///Users/database/Projects/nativephp/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/database/Projects/nativephp/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:24736:24)
    at file:///Users/database/Projects/nativephp/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:24698:26`

**Comment by NBA707** [comment]
Ah, I updated my composer.json to have: nativephp/electron 0.6.2 and it now builds without error
