### ISSUE TITLE
The windows built app shows nothing, (using nativphp/electron `v0.6.3` and higher)

### ISSUE THREAD

**Issue by mohamedds-12** [NativePHP/laravel#314]
### What were you trying to do?

I tried to build the app using `php artisan native:build`

### What happened?

The build completed, but whenI run the app nothing happens, it stays in hte background, and for some how there is a lot of occurrences :
![image](https://github.com/NativePHP/laravel/assets/92916932/a58bf1e7-c269-49f0-9d8b-da3874503ec9)

### How to reproduce the bug

build the app and run it

### Package Versions

nativephp/electron 0.6.3 | 0.6.5

### PHP Version

8.1.10

### Laravel Version

10.48.10

### Node Version

20.1.0

### Which operating systems have you seen this occur on?

Windows

### OS version

10.0.19045 N/A Build 19045

**Comment by Rudeisnice** [comment]
Whats the Error it reports when you start the laravel.exe with CMD?

**Comment by mohamedds-12** [comment]
> Whats the Error it reports when you start the laravel.exe with CMD?

```
(node:16500) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure from null
    at Object.setAppUserModelId (C:\Users\Mohammed\AppData\Local\Programs\laravel\resources\app.asar\node_modules\@electron-toolkit\utils\dist\index.js:215:26)
    at NativePHP.<anonymous> (C:\Users\Mohammed\AppData\Local\Programs\laravel\resources\app.asar\node_modules\@nativephp\electron-plugin\dist\index.js:108:33)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Mohammed\AppData\Local\Programs\laravel\resources\app.asar\node_modules\@nativephp\electron-plugin\dist\index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `laravel --trace-warnings ...` to show where the warning was created)
(node:16500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by mohamedds-12** [comment]
After updating to electro v 0.6.5, The output when I lunch the app using terminal : 
```
Error: spawn C:\Users\Mohamed DS\AppData\Local\Programs\inspirational-quote\resources\app.asar.unpacked\resources\php\php.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\Mohamed DS\\AppData\\Local\\Programs\\inspirational-quote\\resources\\app.asar.unpacked\\resources\\php\\php.exe',
  path: 'C:\\Users\\Mohamed DS\\AppData\\Local\\Programs\\inspirational-quote\\resources\\app.asar.unpacked\\resources\\php\\php.exe',
  spawnargs: [ 'artisan', 'native:config' ],
  cmd: 'C:\\Users\\Mohamed DS\\AppData\\Local\\Programs\\inspirational-quote\\resources\\app.asar.unpacked\\resources\\php\\php.exe artisan native:config',
  stdout: '',
  stderr: ''
}
Error: spawn C:\Users\Mohamed DS\AppData\Local\Programs\inspirational-quote\resources\app.asar.unpacked\resources\php\php.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\Mohamed DS\\AppData\\Local\\Programs\\inspirational-quote\\resources\\app.asar.unpacked\\resources\\php\\php.exe',
  path: 'C:\\Users\\Mohamed DS\\AppData\\Local\\Programs\\inspirational-quote\\resources\\app.asar.unpacked\\resources\\php\\php.exe',
  spawnargs: [ 'artisan', 'native:php-ini' ],
  cmd: 'C:\\Users\\Mohamed DS\\AppData\\Local\\Programs\\inspirational-quote\\resources\\app.asar.unpacked\\resources\\php\\php.exe artisan native:php-ini',
  stdout: '',
  stderr: ''
}
(node:8900) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure from undefined
    at Object.setAppUserModelId (C:\Users\Mohamed DS\AppData\Local\Programs\inspirational-quote\resources\app.asar\node_modules\@electron-toolkit\utils\dist\index.js:215:26)
    at NativePHP.<anonymous> (C:\Users\Mohamed DS\AppData\Local\Programs\inspirational-quote\resources\app.asar\node_modules\@nativephp\electron-plugin\dist\index.js:108:33)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Mohamed DS\AppData\Local\Programs\inspirational-quote\resources\app.asar\node_modules\@nativephp\electron-plugin\dist\index.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:8900) TypeError: Error processing argument at index 0, conversion failure from undefined
    at Object.setAppUserModelId (C:\Users\Mohamed DS\AppData\Local\Programs\inspirational-quote\resources\app.asar\node_modules\@electron-toolkit\utils\dist\index.js:215:26)
    at NativePHP.<anonymous> (C:\Users\Mohamed DS\AppData\Local\Programs\inspirational-quote\resources\app.asar\node_modules\@nativephp\electron-plugin\dist\index.js:108:33)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Mohamed DS\AppData\Local\Programs\inspirational-quote\resources\app.asar\node_modules\@nativephp\electron-plugin\dist\index.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Dalovec** [comment]
I have the same problem as @mohamedds-12. The windows built app doesn't launch. Building on windows or mac doesn't change this behaviour.

**Comment by umair982** [comment]
I am also having same problem. same error when tried to run app on terminal. @mohamedds-12 did you get solution or did you fixed it ? if yes kindly share

**Comment by mohamedds-12** [comment]
> I am also having same problem. same error when tried to run app on terminal. @mohamedds-12 did you get solution or did you fixed it ? if yes kindly share 

Nope no solution so far

**Comment by kdrmlhcn** [comment]
Is there any solution? I have same problem on Windows.

**Comment by kdrmlhcn** [comment]
> I have the same problem as @mohamedds-12. The windows built app doesn't launch. Building on windows or mac doesn't change this behaviour. I am on v0.6.5.

Did you find any solution?

**Comment by mohamedds-12** [comment]
Sadly still no luck

> > I have the same problem as @mohamedds-12. The windows built app doesn't launch. Building on windows or mac doesn't change this behaviour. I am on v0.6.5.
> 
> Did you find any solution?

Sadly still no luck

**Comment by discoverlance-com** [comment]
I also have a similar problem and I debugged for a very long time, over the past 2 days thinking that I am doing something wrong because the same app when I build it for linux, it launches but on Windows, it just shows up in the task manager as  a task but now window shows up...

**Comment by simonhamp** [comment]
Could someone please test a Windows build with the latest releases, [nativephp/laravel v0.6.2](https://github.com/NativePHP/laravel/releases/tag/0.6.2) and [nativephp/electron v0.8.5](https://github.com/NativePHP/electron/releases/tag/0.8.5) and report back here?

**Comment by mohamedds-12** [comment]
> Could someone please test a Windows build with the latest releases, [nativephp/laravel v0.6.2](https://github.com/NativePHP/laravel/releases/tag/0.6.2) and [nativephp/electron v0.8.5](https://github.com/NativePHP/electron/releases/tag/0.8.5) and report back here?

@simonhamp, Same thing, Error message when excuting using terminal : 
```
(node:12092) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure from null
    at Object.setAppUserModelId (C:\Users\Mohammed\AppData\Local\Programs\wisdom\resources\app.asar\node_modules\@electron-toolkit\utils\dist\index.cjs:18:20)
    at NativePHP.setAppUserModelId (C:\Users\Mohammed\AppData\Local\Programs\wisdom\resources\app.asar\out\main\index.js:1726:23)
    at NativePHP.<anonymous> (C:\Users\Mohammed\AppData\Local\Programs\wisdom\resources\app.asar\out\main\index.js:1697:12)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Mohammed\AppData\Local\Programs\wisdom\resources\app.asar\out\main\index.js:1626:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `wisdom --trace-warnings ...` to show where the warning was created)
(node:12092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by marcanthonysurmont** [comment]
I have this exact same problem, still no updates on this?

**Comment by mohamedds-12** [comment]
@simonhamp Anything on this ?

**Comment by PeteBishwhip** [comment]
@mohamedds-12 - Could you please confirm if this issue persists using the latest `1.0.0` versions of `nativephp/electron` and `nativephp/laravel`?

I can confirm that I have a NativePHP app that was built for Mac and Windows and both versions are working as expected.

If it still doesn't work, please try whilst creating a new Laravel app and building that prior to adding any custom logic. If that builds, it would indicate a possible issue with your code.

If it isn't working, please provide some valuable reproduction steps so that I can reproduce your issue. For example:

1. Create a new Laravel 11 app
2. Run `composer require nativephp/electron`
3. Run `php artisan native:install`
4. Run `npm i && npm run build`
5. Run `php artisan native:build win`

By providing these steps, we'll be more likely to reproduce the issue and identify if there is any issue.

I look forward to hearing back from you.

Thanks! :)

**Comment by mohamedds-12** [comment]
@PeteBishwhip After upgrading to version `1.0.0` it worked 🎉
Thanks a lot for developing such an amazing package.

**Comment by PeteBishwhip** [comment]
I see that this has been reopened without any additional input or context and the previous comment about the issue being resolved has been removed. 

Are you still facing this issue?

**Comment by mohamedds-12** [comment]
Sorry for not responding earlier, after upgrading to laravel v11 the app was built with no error, Thanks for ur efforts.
