### ISSUE TITLE
[Bug]: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile

### ISSUE THREAD

**Issue by JayBizzle** [NativePHP/laravel#45]
### What happened?

Running `artisan nativephp:serve` produces a `yarn` error

### How to reproduce the bug

Run `artisan nativephp:serve`

### Package Version

0.1.0

### PHP Version

8.2.6

### Laravel Version

10.15.0

### Which operating systems does with happen with?

macOS

### Notes

This is the error i get when trying to get this running on my MacBook. As a side note, i have had this running successfully on my Mac Studio, so not sure what's going on here 😕 

```bash
Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…
Internal Error: NativePHP@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at V0.getCandidates (/Users/user/.volta/tools/image/yarn/3.6.1/bin/yarn.js:435:5145)
    at kf.getCandidates (/Users/user/.volta/tools/image/yarn/3.6.1/bin/yarn.js:391:1264)
    at /Users/user/.volta/tools/image/yarn/3.6.1/bin/yarn.js:439:8033
    at df (/Users/user/.volta/tools/image/yarn/3.6.1/bin/yarn.js:390:11070)
    at ge (/Users/user/.volta/tools/image/yarn/3.6.1/bin/yarn.js:439:8013)
    at async Promise.allSettled (index 0)
    at async io (/Users/user/.volta/tools/image/yarn/3.6.1/bin/yarn.js:390:10398)
    at async /Users/user/.volta/tools/image/yarn/3.6.1/bin/yarn.js:439:8545
    at async ti.startProgressPromise (/Users/user/.volta/tools/image/yarn/3.6.1/bin/yarn.js:390:47579)
    at async je.resolveEverything (/Users/user/.volta/tools/image/yarn/3.6.1/bin/yarn.js:439:6573)
```

**Comment by kendaniels** [comment]
Same problem here. Got past issue #27 and then encountered this.
