### ISSUE TITLE
[Bug]: his package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile

### ISSUE THREAD

**Issue by nomanur** [NativePHP/laravel#49]
### What happened?

after running php artisan native:serve it shows this

This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at V0.getCandidates (/home/noman/www/native/.yarn/releases/yarn-3.6.1.cjs:435:5145)
    at kf.getCandidates (/home/noman/www/native/.yarn/releases/yarn-3.6.1.cjs:391:1264)
    at /home/noman/www/native/.yarn/releases/yarn-3.6.1.cjs:439:8033
    at df (/home/noman/www/native/.yarn/releases/yarn-3.6.1.cjs:390:11070)
    at ge (/home/noman/www/native/.yarn/releases/yarn-3.6.1.cjs:439:8013)

### How to reproduce the bug

php artisan native:serve

### Package Version

1.0.0

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by ddobren** [comment]
Hello, I will check your problem.
As NativePHP is relatively **new**, it is possible to encounter a few bugs.

**Comment by olssonm** [comment]
Duplicate of #45.

Also, please not that NativePHP only supports macOS for now. Linux and Windows support is incoming.
