### ISSUE TITLE
[Bug]: Sub-Minute Scheduling not working

### ISSUE THREAD

**Issue by SamuelNitsche** [NativePHP/laravel#72]
### What happened?

When trying to use the new sub minute scheduling, the (in my case) scheduled command only gets executed every minute.

### How to reproduce the bug

1. Setup a fresh project
2. Create a command and write the current date and time to the log
3. Start the app using `native:serve`
4. Check the logs and verify it only writes every minute

### Package Version

0.1.1

### PHP Version

8.2.8

### Laravel Version

10.16.1

### Node Version

18.15.0

### Which operating systems does with happen with?

macOS

**Comment by simonhamp** [comment]
Can you share your `app/Console/Kernel.php` definition for this task?

**Comment by SamuelNitsche** [comment]
Today while again trying this in a new project I noticed something interesting. _Sometimes_ this works perfectly fine but not always. 

My Kernel file looks like this:
```
<?php

namespace App\Console;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{
    /**
     * Define the application's command schedule.
     */
    protected function schedule(Schedule $schedule): void
    {
        $schedule->command('test')->everyThirtySeconds();
    }

    /**
     * Register the commands for the application.
     */
    protected function commands(): void
    {
        $this->load(__DIR__.'/Commands');

        require base_path('routes/console.php');
    }
}
```

The command:
```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class WriteTimeToLogCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Write time to log';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        \Log::info('The current time is ' . date('Y-m-d H:i:s'));
    }
}
```

This produces the following log file. See how the output sometimes is correct, sometimes isn't. I feel like this is either fully random or has something to do with window focus. 

```
[2023-07-27 09:56:56] local.INFO: The current time is 2023-07-27 09:56:56  
[2023-07-27 09:57:56] local.INFO: The current time is 2023-07-27 09:57:56  
[2023-07-27 09:57:59] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowFocused] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 09:58:56] local.INFO: The current time is 2023-07-27 09:58:56  
[2023-07-27 09:59:56] local.INFO: The current time is 2023-07-27 09:59:56  
[2023-07-27 10:00:15] local.ERROR: There are no commands defined in the "websockets" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"websockets\" namespace. at /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php:657)
[stacktrace]
#0 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(708): Symfony\\Component\\Console\\Application->findNamespace('websockets')
#1 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->find('websockets:serv...')
#2 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"} 
[2023-07-27 10:00:15] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowShown] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:00:15] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowFocused] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:01:15] local.INFO: The current time is 2023-07-27 10:01:15  
[2023-07-27 10:01:45] local.INFO: The current time is 2023-07-27 10:01:45  
[2023-07-27 10:02:12] local.ERROR: There are no commands defined in the "websockets" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"websockets\" namespace. at /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php:657)
[stacktrace]
#0 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(708): Symfony\\Component\\Console\\Application->findNamespace('websockets')
#1 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->find('websockets:serv...')
#2 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"} 
[2023-07-27 10:02:12] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowFocused] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:02:12] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowShown] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:02:12] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowBlurred] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:03:12] local.INFO: The current time is 2023-07-27 10:03:12  
[2023-07-27 10:03:42] local.INFO: The current time is 2023-07-27 10:03:42  
[2023-07-27 10:03:58] local.ERROR: There are no commands defined in the "websockets" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"websockets\" namespace. at /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php:657)
[stacktrace]
#0 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(708): Symfony\\Component\\Console\\Application->findNamespace('websockets')
#1 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->find('websockets:serv...')
#2 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"} 
[2023-07-27 10:03:58] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowShown] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:03:58] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowFocused] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:03:59] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowClosed] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:04:58] local.INFO: The current time is 2023-07-27 10:04:58  
[2023-07-27 10:05:58] local.INFO: The current time is 2023-07-27 10:05:58  
[2023-07-27 10:06:46] local.ERROR: There are no commands defined in the "websockets" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"websockets\" namespace. at /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php:657)
[stacktrace]
#0 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(708): Symfony\\Component\\Console\\Application->findNamespace('websockets')
#1 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->find('websockets:serv...')
#2 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"} 
[2023-07-27 10:06:47] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowShown] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:06:47] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowFocused] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:06:49] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowClosed] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:07:47] local.INFO: The current time is 2023-07-27 10:07:47  
[2023-07-27 10:08:47] local.INFO: The current time is 2023-07-27 10:08:47  
[2023-07-27 10:08:58] local.ERROR: There are no commands defined in the "websockets" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"websockets\" namespace. at /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php:657)
[stacktrace]
#0 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(708): Symfony\\Component\\Console\\Application->findNamespace('websockets')
#1 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->find('websockets:serv...')
#2 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"} 
[2023-07-27 10:08:58] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowShown] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:08:58] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowFocused] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:09:03] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowBlurred] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:09:58] local.INFO: The current time is 2023-07-27 10:09:58  
[2023-07-27 10:10:58] local.INFO: The current time is 2023-07-27 10:10:58  
[2023-07-27 10:11:03] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowFocused] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:11:13] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowBlurred] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:11:20] local.ERROR: There are no commands defined in the "websockets" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"websockets\" namespace. at /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php:657)
[stacktrace]
#0 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(708): Symfony\\Component\\Console\\Application->findNamespace('websockets')
#1 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->find('websockets:serv...')
#2 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /Users/samuelnitsche/Sites/nativephp-sub-minute-scheduling/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"} 
[2023-07-27 10:11:20] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowShown] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:11:20] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowFocused] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:12:20] local.INFO: The current time is 2023-07-27 10:12:20  
[2023-07-27 10:12:50] local.INFO: The current time is 2023-07-27 10:12:50  
[2023-07-27 10:13:06] local.INFO: Broadcasting [Native\Laravel\Events\Windows\WindowBlurred] on channels [nativephp] with payload:
{
    "id": "main",
    "socket": null
}  
[2023-07-27 10:13:20] local.INFO: The current time is 2023-07-27 10:13:20  
[2023-07-27 10:13:50] local.INFO: The current time is 2023-07-27 10:13:50  
```

**Comment by mpociot** [comment]
Thanks for providing an example repo @SamuelNitsche this helped me track down the issue.
Sub-minute scheduling works by ensuring that the scheduler runs exactly at the start of a new minute. This is why some of your scheduled tasks worked (depending on when the scheduler was started) and others didn't.

I added a delay to ensure that we start at the full minute now.
