### ISSUE TITLE
[Bug]: On Linux (Ubuntu) 

### ISSUE THREAD

**Issue by FrankFlow** [NativePHP/laravel#74]
### What happened?

`francesco@francesco-Aspire-A515-45:~/Scrivania/e-sites/native$ php artisan native:install
Publishing NativePHP Service Provider...

 Would you like to install the NativePHP NPM dependencies? (yes/no) [yes]:
 > y

Fetching latest dependencies…

> NativePHP@1.0.0 postinstall
> electron-builder install-app-deps

  • electron-builder  version=24.6.2
Binary Source:  /home/francesco/Scrivania/e-sites/native/vendor/nativephp/php-bin/bin/mac
Binary Filename:  php
Arch:  x64
Platform:  linux
Copying PHP file(s) from /home/francesco/Scrivania/e-sites/native/vendor/nativephp/php-bin/bin/mac/x64 to /home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/resources/php
Error copying PHP binary Error: ENOENT: no such file or directory, stat '/home/francesco/Scrivania/e-sites/native/vendor/nativephp/php-bin/bin/mac/x64'
    at Object.statSync (node:fs:1591:3)
    at Object.statSync (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/node_modules/graceful-fs/polyfills.js:318:34)
    at statSync (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/node_modules/fs-extra/lib/util/stat.js:10:52)
    at getStatsSync (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/node_modules/fs-extra/lib/util/stat.js:24:19)
    at Object.checkPathsSync (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/node_modules/fs-extra/lib/util/stat.js:49:33)
    at copySync (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at Object.<anonymous> (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/electron-builder.js:48:9)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1051:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at readConfig (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/node_modules/read-config-file/src/main.ts:20:14)
    at findAndReadConfig (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/node_modules/read-config-file/src/main.ts:48:18)
    at getConfig (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/node_modules/app-builder-lib/src/util/config.ts:44:34) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/francesco/Scrivania/e-sites/native/vendor/nativephp/php-bin/bin/mac/x64'
}
Copied certificate file to /home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/resources/cacert.pem
  • loaded configuration  file=/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/electron-builder.js

up to date, audited 560 packages in 2s

79 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 Would you like to start the NativePHP development server (yes/no) [no]:
 > y   

Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…

> NativePHP@1.0.0 dev
> electron-vite dev --watch

vite v4.4.6 building for development...

watching for file changes...

build started...
✓ 3 modules transformed.

build the electron main process successfully

-----

Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
file: /home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/src/main/index.js
vite v4.4.6 building for development...

watching for file changes...

build started...
"contextBridge" and "ipcRenderer" are imported from external module "electron" but never used in "src/preload/index.js".
✓ 1 modules transformed.
out/preload/index.js  0.70 kB
built in 61ms.

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
error during start dev server and electron app:
Error: No electron app entry file found: /home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/out/main/index.js
    at ensureElectronEntryFile (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/chunks/lib-e45cc666.js:26:23)
    at Object.startElectron (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/chunks/lib-e45cc666.js:120:5)
    at createServer (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/chunks/lib-25a7a89c.js:74:21)
    at async CAC.<anonymous> (/home/francesco/Scrivania/e-sites/native/vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/cli.js:48:9)
NativePHP scaffolding installed successfully.
`

### How to reproduce the bug

I tryed this [workaround](https://github.com/NativePHP/electron/issues/10) , too.

### Package Version

0.2.0

### PHP Version

8.1.12

### Laravel Version

10.16.1

### Node Version

18.13

### Which operating systems does with happen with?

Linux

**Comment by GB-JUUBY** [comment]
Same here ;(

**Comment by RicardoJarquin** [comment]
Linux OS is not supported yet, but the PR is pending approval, wait just a few, I hope today or tomorrow will be merged the fix

**Comment by ArtMin96** [comment]
Possible fix: https://github.com/NativePHP/electron/pull/57

**Comment by simonhamp** [comment]
Could you try updating to the latest version (0.6.1) to see if this has been resolved in the various updates made since 0.2?
