### ISSUE TITLE
[Bug]: Could not resolve "../../resources/php/php?asset&asarUnpack" when building app on macOS

### ISSUE THREAD

**Issue by Rueff19** [NativePHP/laravel#77]
### What happened?

when trying to build the app an error is thrown:

```
vite v4.4.7 building for production...
✓ 2 modules transformed.
✓ built in 13ms
Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
file: /Users/me/Sites/laravel-example/vendor/nativephp/electron/resources/js/src/main/index.js
error during build:
RollupError: Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
    at error (file:///Users/me/Sites/laravel-example/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/me/Sites/laravel-example/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:24654:24)
    at file:///Users/me/Sites/laravel-example/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:24616:26
```

### How to reproduce the bug

Run `php artisan native:build` on macOS

### Package Version

0.3.0

### PHP Version

8.2.0

### Laravel Version

10.15.0

### Node Version

18.15.0

### Which operating systems does with happen with?

macOS

### Notes

using an M2 chip

**Comment by Rueff19** [comment]
Closing this issue.
When I switched to SQLite the error no longer exists.

**Comment by secondmanveran** [comment]
I'm having this exact issue on an Intel Core i9, and I am using SQLite.

Should I open a new issue?
